//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renew_Laptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP2LOCATION
    {
        public int ID { get; set; }
        public string IP_From { get; set; }
        public string IP_To { get; set; }
        public string Code { get; set; }
        public string Country { get; set; }
    }
}
